function klay(){var ab='',Z=' top: -1000px;',tb='" for "gwt:onLoadErrorFn"',rb='" for "gwt:onPropertyErrorFn"',ub='#',Vb='.cache.js',wb='/',Cb='//',Pb='574909C9C3AE2896898FE135FF870BA7',Qb='7108263F4F1B8B2CDDBC3A827374125C',Ub=':',lb='::',ac=':moduleBase',_='<!doctype html>',bb='<html><head><\/head><body><\/body><\/html>',ob='=',vb='?',Rb='A039C686CC12796C3A99BE11CF05F159',Sb='B2D684F23A542730E1336458A9E18209',qb='Bad handler "',$='CSS1Compat',Tb='D046BB5E0BCEF982C51876913D6AE89E',db='DOMContentLoaded',U='DUMMY',_b='Ignoring non-whitelisted Dev Mode URL: ',$b='__gwtDevModeHook:klay',Bb='base',zb='baseUrl',P='begin',V='body',O='bootstrap',yb='clear.cache.gif',nb='content',Xb='end',Zb='file:',Kb='gecko',Lb='gecko1_8',Q='gwt.codesvr.klay=',R='gwt.codesvr=',sb='gwt:onLoadErrorFn',pb='gwt:onPropertyErrorFn',mb='gwt:property',bc='head',Yb='http:',Hb='ie10',Jb='ie8',Ib='ie9',W='iframe',xb='img',fb='javascript',X='javascript:""',S='klay',Ob='klay.devmode.js',Ab='klay.nocache.js',kb='klay::',Wb='loadExternalRefs',ib='meta',hb='moduleRequested',gb='moduleStartup',Gb='msie',jb='name',Y='position:absolute; width:0; height:0; border:none; left: -1000px;',Fb='safari',eb='script',Nb='selectingPermutation',T='startup',cb='undefined',Mb='unknown',Db='user.agent',Eb='webkit';var n=window;var o=document;q(O,P);function p(){var a=n.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function q(a,b){if(n.__gwtStatsEvent){n.__gwtStatsEvent({moduleName:S,sessionId:n.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
klay.__sendStats=q;klay.__moduleName=S;klay.__errFn=null;klay.__moduleBase=U;klay.__softPermutationId=0;klay.__computePropValue=null;klay.__getPropMap=null;klay.__gwtInstallCode=function(){};klay.__gwtStartLoadingFragment=function(){return null};var r=function(){return false};var s=function(){return null};__propertyErrorFunction=null;var t=n.__gwt_activeModules=n.__gwt_activeModules||{};t[S]={moduleName:S};var u;function v(){A();return u}
function w(){A();return u.getElementsByTagName(V)[0]}
function A(){if(u){return}var a=o.createElement(W);a.src=X;a.id=S;a.style.cssText=Y+Z;a.tabIndex=-1;o.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==$?_:ab;u.write(b+bb);u.close()}
function B(f){function g(a){function b(){if(typeof o.readyState==cb){return typeof o.body!=cb&&o.body!=null}return /loaded|complete/.test(o.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(o.removeEventListener){o.removeEventListener(db,d,false)}if(e){clearInterval(e)}}}
if(o.addEventListener){o.addEventListener(db,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function h(a){var b=w();var c=v().createElement(eb);c.language=fb;c.src=a;q(gb,hb);b.appendChild(c)}
g(function(){h(f)})}
klay.__startLoadingFragment=function(a){return F(a)};klay.__installRunAsyncCode=function(a){var b=w();var c=v().createElement(eb);c.language=fb;c.text=a;b.appendChild(c);b.removeChild(c)};function C(){var c={};var d;var e;var f=o.getElementsByTagName(ib);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(jb),k;if(j){j=j.replace(kb,ab);if(j.indexOf(lb)>=0){continue}if(j==mb){k=i.getAttribute(nb);if(k){var l,m=k.indexOf(ob);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=ab}c[j]=l}}else if(j==pb){k=i.getAttribute(nb);if(k){try{d=eval(k)}catch(a){alert(qb+k+rb)}}}else if(j==sb){k=i.getAttribute(nb);if(k){try{e=eval(k)}catch(a){alert(qb+k+tb)}}}}}s=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;klay.__errFn=e}
function D(){function e(a){var b=a.lastIndexOf(ub);if(b==-1){b=a.length}var c=a.indexOf(vb);if(c==-1){c=a.length}var d=a.lastIndexOf(wb,Math.min(c,b));return d>=0?a.substring(0,d+1):ab}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=o.createElement(xb);b.src=a+yb;a=e(b.src)}return a}
function g(){var a=s(zb);if(a!=null){return a}return ab}
function h(){var a=o.getElementsByTagName(eb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Ab)!=-1){return e(a[b].src)}}return ab}
function i(){var a=o.getElementsByTagName(Bb);if(a.length>0){return a[a.length-1].href}return ab}
function j(){var a=o.location;return a.href==a.protocol+Cb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==ab){k=h()}if(k==ab){k=i()}if(k==ab&&j()){k=e(o.location.href)}k=f(k);return k}
function F(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return klay.__moduleBase+a}
function G(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Db]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Eb)!=-1}())return Fb;if(function(){return b.indexOf(Gb)!=-1&&o.documentMode>=10}())return Hb;if(function(){return b.indexOf(Gb)!=-1&&o.documentMode>=9}())return Ib;if(function(){return b.indexOf(Gb)!=-1&&o.documentMode>=8}())return Jb;if(function(){return b.indexOf(Kb)!=-1}())return Lb;return Mb};i[Db]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};r=function(a,b){return b in i[a]};klay.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};klay.__computePropValue=k;n.__gwt_activeModules[S].bindings=klay.__getPropMap;q(O,Nb);if(p()){return F(Ob)}var l;try{h([Ib],Pb);h([Lb],Qb);h([Hb],Rb);h([Fb],Sb);h([Jb],Tb);l=f[k(Db)];var m=l.indexOf(Ub);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}klay.__softPermutationId=g;return F(l+Vb)}
function H(){if(!n.__gwt_stylesLoaded){n.__gwt_stylesLoaded={}}q(Wb,P);q(Wb,Xb)}
C();klay.__moduleBase=D();t[S].moduleBase=klay.__moduleBase;var I=G();if(n){var J=!!(n.location.protocol==Yb||n.location.protocol==Zb);n.__gwt_activeModules[S].canRedirect=J;if(J){var K=$b;var L=n.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(_b+L)}L=ab}if(L&&!n[K]){n[K]=true;n[K+ac]=D();var M=o.createElement(eb);M.src=L;var N=o.getElementsByTagName(bc)[0];N.insertBefore(M,N.firstElementChild||N.children[0]);return false}}}H();q(O,Xb);B(I);return true}
klay.succeeded=klay();